version: "1.0"
services:
  nginx-react:
    container_name: interviewapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development


